
# This file was *autogenerated* from the file helper.sage
from sage.all_cmdline import *   # import sage library

_sage_const_123 = Integer(123); _sage_const_0 = Integer(0); _sage_const_63 = Integer(63); _sage_const_47 = Integer(47); _sage_const_48 = Integer(48); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15); _sage_const_31 = Integer(31); _sage_const_32 = Integer(32)
def print_big(n):
    a = hex(int(n))
    print("a[0] = ", a[_sage_const_0 :_sage_const_15 ])
    print("a[1] = ", a[_sage_const_16 :_sage_const_31 ])
    print("a[2] = ", a[_sage_const_32 :_sage_const_47 ])
    print("a[3] = ", a[_sage_const_48 :_sage_const_63 ])



print_big(_sage_const_123 )

